### ISSUE TITLE
Fix bad alloc error

### ISSUE THREAD

**Issue by rodrigocam** [IJE-Valhalla/Litigium#16]
Sometimes bad alloc error occurs when the game runs for some time. It's not possible to track and make it crash on purpose, probably caused by something with how the game objects are created or printed on the screen using class animation and animation_quads.

**Comment by madduci** [comment]
I'm testing it under Linux and it crashes by each key press at the beginning of a new game.
Looking at the code, I should point out that you use `new` almost everywhere! If you don't mind to embrace at least C++11 standard, you can use smart pointers or work with references, since you can catch easily if something is misused or not allocated and you avoid double-free and memory leaks by forgotten `delete`.

Another fact: the class Color is used everywhere and it's passed as pointer around the codebase. Most of the values are repeated: why don't you define const/constexpr values globally and use them?

I've run also cppcheck against the code, and there are minor warnings on unused variables.

See #19

**Comment by rodrigocam** [comment]
Hi @madduci, we really appreciate your contribution, your pull request was accepeted. The things you pointed in your comment are very relevant. We sorry about the game crashing on pressing keys, it's a really weird thing because in ours computers it's running normally, maybe it can be something in the differences between your keyboard and ours (this is only a guess). We will try to figure out this problem and hope you can keep contributing with this game!

**Comment by madduci** [comment]
You're welcome @rodrigocam. It was not a keyboard issue, but it was caused by bad object lifetime. With my latest pull request, #20, I don't have bad_alloc nor crashes anymore.

**Comment by rodrigocam** [comment]
Issue resolved!
